<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>IFC to BIM Open Schema conversion via the native web-ifc library.</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../vendor/web-ifc-library.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Link>web-ifc-library.dll</Link>
      <Pack>true</Pack>
      <PackagePath>contentFiles/any/any</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ara3D.BimOpenSchema" Version="$(Ara3DBimOpenSchemaVersion)" />
    <ProjectReference Include="..\..\src\Ara3D.IO.StepParser\Ara3D.IO.StepParser.csproj" />
    <ProjectReference Include="..\..\src\Ara3D.Models\Ara3D.Models.csproj" />
  </ItemGroup>

  <Import Project="..\Ara3D.IfcTypes\Ara3D.IfcTypes.projitems" Label="Shared" />
</Project>
