<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="ara3d.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ara3d-32x32.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="$(Ara3DNewtonsoftJsonVersion)" />
    <PackageReference Include="System.Drawing.Common" Version="$(Ara3DSystemDrawingCommonVersion)" />
    <PackageReference Include="System.Runtime.Loader" Version="$(Ara3DSystemRuntimeLoaderVersion)" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Ara3D.BimOpenSchema.IO" Version="$(Ara3DBimOpenSchemaVersion)" />
    <PackageReference Include="Ara3D.BimOpenSchema" Version="$(Ara3DBimOpenSchemaVersion)" />
    <ProjectReference Include="..\..\plugins\Ara3D.Bowerbird.Revit2025\Ara3D.Bowerbird.Revit2025.csproj" />
    <ProjectReference Include="..\..\plugins\Ara3D.Bowerbird.RevitSamples\Ara3D.Bowerbird.RevitSamples.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="AdWindows">
      <HintPath>..\..\vendor\Revit\2025\AdWindows.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPI">
      <HintPath>..\..\vendor\Revit\2025\RevitAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>..\..\vendor\Revit\2025\RevitAPIUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UIFramework">
      <HintPath>..\..\vendor\Revit\2025\UIFramework.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <Target Name="RemoveUnwantedFiles" AfterTargets="Build">
    <Delete Files="$(OutDir)RevitAPI.dll" />
    <Delete Files="$(OutDir)RevitAPIUI.dll" />
    <Delete Files="$(OutDir)AdWindows.dll" />
    <Delete Files="$(OutDir)UIFramework.dll" />
    <Delete Files="$(OutDir)runtimes\**\*.*" />
    <Delete Files="$(OutDir)*.pdb" />
    <RemoveDir Directories="$(OutDir)runtimes" />
  </Target>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="call &quot;$(MSBuildProjectDirectory)\post-build.bat&quot; $(OutDir)" IgnoreExitCode="true" />
  </Target>
</Project>
